### ISSUE TITLE
Leading hyphen "wl- " causes an error upon task entry

### ISSUE THREAD

**Issue by kaspersoerensen** [idpaterson/alfred-wunderlist-workflow#119]
Not really a bug - but maybe some error messaging could be nice.
Example: I punch in the following:
`wl- div: Protocol due 11 may`

Which gives this error:
![skaermbillede 2016-05-03 kl 15 14 11](https://cloud.githubusercontent.com/assets/2018894/14984370/979a0c86-1142-11e6-88a4-e8b193288d39.png)

The error was that I typed `wl-` and then started typing the list name. That was a bit difficult to figure out by the error message.

Version of Alfred-Wunderlist-Workflow: 0.6.0-beta.3

**Comment by idpaterson** [comment]
@kaspersoerensen thanks for reporting, it looks like that hyphen indeed causes a problem when the task is added. The `<?xml` bit suggests that the workflow tried to handle your task entry as a normal query that you typed in to Alfred rather than as an action. When you press <kbd>return</kbd> the workflow includes a `--commit` at the end of the message to indicate that you want to perform the corresponding action, so I wonder if there is a problem parsing that `--commit` syntax when there is a preceding hyphen, as if it's stripping off your "- div: Protocol due 11 may" as another `--` command...

Good find, I'll take a look at that this evening.

**Comment by idpaterson** [comment]
This was an easy fix, it will go out with the next release since it is not a high priority bug.

**Comment by kaspersoerensen** [comment]
Hi,
Nice to hear! I actually just "misused" the command and typed `wl-` as I was first going to search for a task.

**Comment by idpaterson** [comment]
Thanks for following up, just a few more things to finish up before 0.6.0 is released so this will be in the next beta.

**Comment by idpaterson** [comment]
This is fixed in 0.6.0-beta.4
