### ISSUE TITLE
german word für resolves to a reminder

### ISSUE THREAD

**Issue by csteinlehner** [idpaterson/alfred-wunderlist-workflow#135]
Hi,

I'm using this workflow in german language. If I type the word für (for) the r and following whitespace gets converted to a reminder. So if I type something like 
`wl l:blumen für mama kaufen`

I get
`Life – reminder at 19:55 blumen fümama kaufen`

**Comment by idpaterson** [comment]
Ooh, that's not good. This is going to become a very important test case in the work that I'm doing in parsedatetime. I see that it is not a particularly difficult fix but it will be fairly comprehensive to make sure that all parsing treats unicode characters properly.

Since this particular case is within the workflow rather than parsedatetime I can push out a fix for this and similar issues for the Wunderlist-specific parsing but if the same problem affects parsedatetime it might be awhile before dates are fixed since we're working on a major update. What happens if you type the made-up word `fünacht`, does it give you `fü` as the task text with a due date and reminder for 21:00:00?

**Comment by csteinlehner** [comment]
fünfacht works fine. It seems like it has something to do with the combination 'ür'

**Comment by idpaterson** [comment]
Correct, I'll be a little more clear here. Since the patterns that the workflow uses are not correctly handing accented characters like ü the word *für* is interpreted as *fü r*. Since the workflow allows reminders to be specified with the single letter *r* as shorthand for *reminder* (along with other terms like *alarm* and *remind me*) this causes the default reminder to be set. I'll have an update out to fix that for you tomorrow.

Similarly, the *fünacht* fake word case would be handled as *fü nacht* where the word *nacht* (night) is interpreted as 21:00:00. You had an extra *f* in there. I didn't find any real German words that had accented characters in a place that would break date parsing, this might be a bigger problem in other languages though.

**Comment by csteinlehner** [comment]
ah sorry yes, fünacht does exactly what you describe.

**Comment by idpaterson** [comment]
Thank you for confirming. That behavior in parsedatetime will be fixed sometime in the next few months but fortunately in the meantime I have found no real German words that would be affected by this.

**Comment by csteinlehner** [comment]
I don't have an example with something else like that. If I stumble upon another problem I will let you know.

Thanks again for your fast reaction!
