### ISSUE TITLE
Ongoing development for Wunderlist 3?

### ISSUE THREAD

**Issue by davemcnally** [idpaterson/alfred-wunderlist-workflow#43]
Wondering if this is going to be maintained and updated for Wunderlist 3? At the moment, typing in `wl` immediately closes the Alfred pop up before being able to do anything else with Wunderlist 3.

If development isn't continuing on this, any recommendation for a v3 alternative would be greatly appreciated!

**Comment by fharper** [comment]
Do you have some news on this workflow? I tried the last alpha version but didn't work for me.

**Comment by idpaterson** [comment]
Unfortunately, while Wunderlist 3 support was a quick and successful update, OS X Yosemite has left the Wunderlist app inaccessible for scripting. More details in #44. Since Wunderlist does not have support for AppleScript and Yosemite has not yet resolved the UI scripting issues affecting the app, the workflow is on ice.

I'll update the Readme.

**Comment by fharper** [comment]
OK, sorry about that, and thanks for your work!
