### ISSUE TITLE
Every wl* command results in instant redirection to Wunderlist New List dialog [Yosemite]

### ISSUE THREAD

**Issue by awinecki** [idpaterson/alfred-wunderlist-workflow#44]
Hello, I think I've found a bug.

I am using OSX Yosemite, I haven't used this worfklow before the update, so it might be related to Yosemite or not.

I installed the worfklow, then typing "wl" instantly (without hitting enter or any other key) redirects me to the Wunderlist app, and open New list creation dialog. This makes any workflow functionality inaccessible.

Screenshot

![oct 21 2014 17 07](https://cloud.githubusercontent.com/assets/656694/4720842/07dba036-5934-11e4-8c47-89c380da2d35.gif)

**Comment by saqebakhter** [comment]
Why not use a command line tool to interface with wunderlist rather than the Ui -- for wunderlist there seem to be a few implementations of a CLI tool already on github -- would that not work ?

**Comment by idpaterson** [comment]
Let me know if anyone has used a specific tool or library that still works with the official Wunderlist API. I'm open to working with something like that since UI automation seems to now be a dead end. The programming language is relatively moot, but I've found that PHP, perl, and compiled binaries were the most responsive in Alfred. The Python and Applescript interpreters are slow to start (at least when loading the corresponding Alfred workflow libraries) and therefore don't work well for script filters.

The original goals of interacting with the Wunderlist app UI were:
* Offline support – a workflow that uses the API needs to have an active internet connection
* No need to log in – any tool that uses the unofficial API will require the workflow user to log in first
* Wunderlist had plans to add AppleScript bindings – Several years ago now, seems unlikely to happen
* The Wunderlist API was unofficial and not supported  – [this is no longer the case](https://developer.wunderlist.com/documentation)

I missed any announcement about the new Wunderlist API documentation... now I need to start experimenting with it!

**Comment by chrismessina** [comment]
The API seems like the most promising approach. It's amusing that you'd have to round-trip to the server just to add a task locally, but welcome to the cloud.

Would [this](https://developer.wunderlist.com/documentation/endpoints/task) call be what you need?

```
POST a.wunderlist.com/api/v1/tasks
```

**Comment by idpaterson** [comment]
Yes, that is the API reference for posting a task. The sticking point in the workflow is not adding a task (that can still be done successfully by automating keyboard shortcuts like `⌘+N`), but rather the primary things that are no longer possible are:
1. Finding the names of the user's lists (and the localized names of the system lists)
2. Switching the Wunderlist app to the selected list

The UI approach had other limitations (e.g. cannot load lists that are scrolled offscreen) before this but worked reliably for most people. I approached the project with an Applescript codebase due to Wunderlist's plans to add AppleScript bindings (e.g. `tell application "Wunderlist" to add task "some task" in list "some list"`). 

It would likely be possible to strip the workflow down to the `wl some task` command which inserts a task in the current list, and `wlin some task` or `wl Inbox some task` which inserts in the inbox. If that sounds like a good idea to anyone, let me know.

**Comment by idpaterson** [comment]
Perhaps the best approach is to use the API for everything but automatically trigger a sync in the Wunderlist app if it happens to be open, to pull in the new task with minimal delay. 

It would be possible for the workflow to continue to enter tasks via the app rather than through the API for offline support, but I don't think the usability would be acceptable for that since it would not be possible to select the list when offline (since the workflow can no longer activate a specific list in the Wunderlist app).

**Comment by chrismessina** [comment]
Yeah, seems like the most sustainable approach long term is to just bite the bullet and use the web API. Maybe once you have basic support you can reach out to the Wunderlist folks and see if they could add more functional endpoints for your purposes.

**Comment by idpaterson** [comment]
I signed up for API access (private beta). Let's hope for the best, I do want to avoid using the older "unofficial API" that projects like wunderpy use.

**Comment by idpaterson** [comment]
I was granted access to the official API and it is looking pretty good! More in-depth details will be provided later, but at a glance I think it will work very nicely for this workflow.

### API benefits
* It is far easier to set and update task metadata such as starred, completed, due date, etc
* The Wunderlist OS X app updates instantly when changes are made via the API, no need to force a sync for app users
* OAuth 2.0 authentication means that the workflow will never need to see the user's password, and the access key granted to the workflow can be disabled from the user's Wunderlist account if necessary
* Good adhesion to REST principles and consistent input/output formats

### Difficulties
* Currently there is no task search API without which the workflow is somewhat limited or forced to database all tasks
* Smart lists like *Today* are not available, would have to load all tasks then filter by due date
* The API is in a beta stage and changes are likely
* The documentation is quite good, but there are some missing details that have wasted quite a bit of my time

The workflow rewrite is in Python. I will not have a distributable beta ready for awhile, but the progress on the code will be published soon in a new branch. So far the Python workflow is able to handle authentication (OAuth 2.0 login and logout), creating a task in any list (though the lists are not yet cached so this is slow), and creating a new list. I am excited about the possibilities with this new API!

**Comment by chrismessina** [comment]
Thanks for the update. Sounds promising! I wonder how expensive it would be to load all the tasks and filter them. Obviously there's a lot of redundancy with the local Wunderlist app DB, but it'd be interesting to know more about the way that task data is mutated — i.e. is it usually written once and then not updated again, or updated infrequently? If so, then having a read-only reference DB may be useful to look up info through Alfred, and then editing can be handed off to the app, etc. 

I guess if your goal is to have a completely headless (or Alfred-only) Wunderlist experience then maybe that doesn't make sense, but I'd be happy with a small subset of workflow actions, at least in the short term — creating a task, adding it to a list, setting a due date (using natural language processing like Fantastical?), getting tasks from a certain list, etc.

**Comment by idpaterson** [comment]
It is quite expensive to load all the tasks but the revision tracking is modular enough that the workflow would only sync tasks in the list where a task was changed. For example, if I add a new task to my Automotive list, the `revision` of the Automotive list is incremented along with the root-level `revision`. There are still a number of HTTP requests involved to find what actually changed but at least it doesn't require requesting every single task or updating anything that did not actually change. I have been working through the sync but it is quite a chore.

There was an extension for Alfred 1 that used Wunderlist.app's database. I think the app at that point in time was using Core Data so the tables were quite a mess and editing them probably caused a lot of problems.

We're on the same wavelength for the initial direction of the API-supported workflow. I'm a big fan of Fantastical and was delighted to find [parsedatetime](/bear/parsedatetime) which can convert "change the cabin air filter next Tuesday" to a datetime.

**Comment by idpaterson** [comment]
The nlp from parsedatetime is fast and works quite well. This sort of a guided view might be more useful for creating a task. Showing the lists during task entry (current behavior) is not as useful and I can't get it faster than about 200ms which is too slow for a script filter. 

Newbies can action the help fields but the subtitles remind power users how to just type what they need. Clearly needs icons and such, but I think this is going in the right direction.

![screen shot 2015-02-16 at 9 40 31 pm](https://cloud.githubusercontent.com/assets/507058/6222594/921acf2c-b624-11e4-9c60-d18cd00b5e5f.png)

**Comment by chrismessina** [comment]
I presume you saw that a [public API](https://www.wunderlist.com/blog/wunderlist-folders-quick-add-android-lollipop/) is coming soon?

**Comment by idpaterson** [comment]
Correct, take a look at the comments on #49 for a preview of what the new API-supported workflow looks like. It should jive nicely with the new Quick Add feature in Wunderlist.

I will have a demo available to test soon. Since Folders haven't hit the API yet we're still just working with lists.

**Comment by idpaterson** [comment]
And now with today's Wunderlist.app update, the icons in the workflow are all outdated =)

**Comment by idpaterson** [comment]
Please download the alfredworkflow file attached to the [first beta release](/idpaterson/alfred-wunderlist-workflow/releases/tag/0.4.0-beta.1). If you notice any bugs please open new issues. I plan to close this issue soon since it will be resolved in 0.4.0.

**Comment by chrismessina** [comment]
Woohoo! That's awesome! The first time I typed WL after authorizing the workflow, I tried to go to Prefs, but got a nasty error. Expected?

**Comment by idpaterson** [comment]
Oh I bet it doesn't like showing the preferences before your User is synced. I'll look into that after some of the more pressing issues are sorted out, thanks for reporting.

**Comment by idpaterson** [comment]
Applescript workflow, soon you will rest in peace. Fortunately this entire mess is resolved by the public API and there are many more avenues for new features in the workflow.
