### ISSUE TITLE
German Shortcut "Fr." sets due date to Friday

### ISSUE THREAD

**Issue by ckoeberle** [idpaterson/alfred-wunderlist-workflow#81]
`wl Fr. Mustermann anrufen`, which means `wl call Mrs. Mustermann` sets a due date to Friday and the subject is `. Mustermann anrufen`

The same happens if i use the shortcuts for Monday (mo) and Saturday (sa), but not for the other weekdays.

**Comment by idpaterson** [comment]
I have tried to think of a good way to ignore things that incorrectly parse as dates but it's not particularly easy to do so. Since the workflow will never be clever enough to know from surrounding context whether you're talking about a time or a different word (for example the same problem exists in English where the abbreviation for Saturday "sat" is also a word with a different meaning).

One approach might be a mode that *requires* the due, repeat, remind keywords. That would allow you to get expected results from `wl Fr. Mustermann anrufen` as well as `wl Fr. Mustermann anrufen due fr`. That would be the easiest to implement since it does not require any changes to parsedatetime and it would take care of the most likely cause of incorrect parsing which is handling for dates without the due keyword. 

Would you be okay with a preference in `wl:pref` to toggle whether the due keyword is required? Or is this better served as a per-task override with a keyword like `wl Fr. Mustermann anrufen not due`?

Parsedatetime defines the following weekday abbreviations for your locale `'mo', 'di', 'mi', 'do', 'fr', 'sa', 'so'`, are those correct?

**Comment by ckoeberle** [comment]
> Would you be okay with a preference in wl:pref to toggle whether the due keyword is required?

absolutely!

**Comment by idpaterson** [comment]
That sounds like a good start! There has been some discussion over at parsedatetime about a parsing mode that ignores or gives a lower "score" to abbreviations like that. It would be a good long-term solution to be less aggressive in pulling out dates when there is no `due` keyword.

**Comment by idpaterson** [comment]
Please give [this update](https://copy.com/8e0bGqa0UJeRJHYz/Wunderlist-not-due.alfredworkflow?download=1) a try when you get a chance. A preference has been added to disable implicit due dates like your example so that the `due` keyword is required. Semi-implicit recurrence (e.g. `wl Recycling weekly` annually, daily, monthly) is still allowed with that setting because disabling that wasn't as straightforward.

There is also a new "not due" or "no due date" keyword that will prevent any due date from being extracted on a case-by-case basis. 

So now you should be able to do `wl Fr. Mustermann anrufen` with the preference enabled and not have a due date, or `wl Fr. Mustermann anrufen not due` with the preference disabled (still the default).

Finally, I wanted to ask how the experience is using this workflow with the mix of German and English keywords. Do you find it confusing or think it is a bad experience for new users to have this mix? I've been considering adding a preference to let users choose English as the locale for parsedatetime until the workflow and parsedatetime are more fully translated... would you use that setting or think it useful for others?

I have tried to discuss localization and translations with other workflow developers but there is a resounding sentiment that since Alfred is English only there is no demand for translated workflows. I suspect that is not the case here since the users of this workflow are largely outside the US. Since German is fairly well-supported in parsedatetime, should the workflow provide a full translation for that language? It add some difficulty to deploying new features, but hopefully the community is active enough to help contribute translations. What do you think? I think this would be important for releasing a version 1.0, not an immediate effort since it is probably more important to round out the feature set first.

**Comment by ckoeberle** [comment]
works great, thx!

> Finally, I wanted to ask how the experience is using this workflow with the mix of German and English keywords. Do you find it confusing or think it is a bad experience for new users to have this mix?

Personally, I don't find it confusing. I'm used to mix these things especially in the context of datetime. Many products use a mix and: "due" is shorter than "fällig am" ;-)

**Comment by idpaterson** [comment]
This was released in [0.5.0-beta.2](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.5.0-beta.2)
