### ISSUE TITLE
Task editing feature requests

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#94]
> If you have not yet downloaded [version 0.6.0-alpha.1](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-alpha.1), please consider doing so if you would like to help test the next big update to the workflow. 

The workflow includes a screen for editing tasks that you may have found via a search or from your due tasks. There are many possibilities for this screen, but I want to identify and focus on the most useful features first.

![task screen](https://cloud.githubusercontent.com/assets/507058/13097837/b5f65cd4-d4f2-11e5-82a5-01b1c7564741.png)

The screen is currently very sparse; at a minimum the screen needs to show all of the task details like on the search results page. I started with the most obvious feature – toggling completion. Hold the `Option` key while completing a recurring event to mark it due today so that the next recurrence is relative to today (this isn't working for me at the moment, not sure why).

For editing tasks, one option is try using the same syntax used to create a task in the workflow. Anything that is specified gets overridden. I need to think through that a bit since the task parser currently always starts with a blank slate. There are a few cases where it would make the wrong choice if it did not know the existing due date and reminder date. 

For example, `wl-task 1440836011 tomorrow *` would update the due date to tomorrow and star the task, and `wl-task 1440836011 every month Monthly #Bookkeeping` would update the task title to "Monthly #Bookkeeping" and the recurrence to monthly.

With that task editing in place, this screen would only need "buttons" for actions that cannot be represented in the task syntax, like subtasks, notes, assignees, making a copy of the task. I'm just not sure which would be most useful.

I want to reach out for ideas to identify some common task-level actions that you would like to access through Alfred or that might take multiple clicks in the Wunderlist app. Thoughts?

**Comment by idpaterson** [comment]
It might be useful to be able to skip one occurrence of a task... normally I would just mark a weekly recurring task complete even if it is irrelevant for a given week (like my reminder to prep for my weekly meeting since there is no meeting tomorrow). For the sake of having a clean history of task completions it would be nice to be able to advance the task to the next due date. Any reminder would have to be advanced as well.

**Comment by wcsherrod** [comment]
Editing task titles, dates and starred status as shown in the example doesn't seem to work for me on 0.6.0-alpha.1. 

Changing starred status directly from the task menu would be the most straightforward method. An option for unstarring currently starred tasks would also be nice if it's not already a feature (I can't get it to work if it is).

**Comment by idpaterson** [comment]
Thanks for the ideas, I am glad to hear that you make use of stars and would find the task editing concept useful. I haven't started working on the task editing syntax yet, but do still plan to include it in 0.6.0. 

There are a few other features that might not make the cut since I have not gotten much feedback on the betas and there are still a few sync issues to work out.

**Comment by sollymay** [comment]
one great idea is to show a limited amount of characters displayed on the notes (as many as your alfred window allows), so that you actually don'y even have to open wunderlist for some of the tasks. If the task comment or notes are to long, then press enter to switch to wunderlist to that specific task so that you can read the whole task.

**Comment by idpaterson** [comment]
Good idea, do you use notes heavily? I only have a few tasks with notes but was thinking about the possibility of opening up a system text editor to view and edit them. It would be tough to do the "correct thing" within Alfred in a way that would make sense for most everyone. Currently notes are not synced so I don't suspect that will make it into 0.6.0 but it seems like a useful future addition.

**Comment by idpaterson** [comment]
@sollymay, I almost missed an important part of your suggestion, the thought of linking to the task in the Wunderlist app... I just played around with the `wunderlist://` URL scheme and found that I can indeed open the app to a specific task. It doesn't fully support the URL paths provided by the web app (e.g. focusing specific fields), but I can at least open it up to a task which will *definitely* go in 0.6.0!

**Comment by sollymay** [comment]
Nice!!! that is actually extremely helpful for me and my workflow. Yes, I use
notes heavily because sometimes I want to store certain websites and info on
the notes. Realistically speaking, the editor part although it seems useful,
will incur in more dev time for you and I think that being able to preview
some of the content will be beneficial. when you actually hit enter, you could
go to the task itself and edit the notes, so I think that it would be more
than enough (at least for me) to be able to preview the notes within alfred.  
  
Sent from [Nylas N1](https://link.nylas.com/link/ejg5mh00zu79xwfmhbchm8cs8
/local-74e1d326-3e7b/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1), the
extensible, open source mail client.  
![](https://link.nylas.com/open/ejg5mh00zu79xwfmhbchm8cs8/local-74e1d326-3e7b)

On Apr 28 2016, at 2:56 pm, Ian Paterson &lt;notifications@github.com&gt;
wrote:  

> [@sollymay](https://github.com/sollymay), I almost missed an important part
of your suggestion, the thought of linking to the task in the Wunderlist
app... I just played around with the wunderlist:// URL scheme and found that I
can indeed open the app to a specific task. It doesn't fully support the URL
paths provided by the web app (e.g. focusing specific fields), but I can at
least open it up to a task which will _definitely_ go in 0.6.0!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/94#iss
uecomment-215527847)![](https://github.com/notifications/beacon/AGMhumvMCi2CEQ
1dYNjqJ0twiPsE0-6Lks5p8QLJgaJpZM4HcG8c.gif)

**Comment by idpaterson** [comment]
Agreed, that will very nicely provide access to all of the task-specific features that will not soon–or in some cases ever–be supported directly in the workflow.

**Comment by idpaterson** [comment]
Yep I like this. I'll release a beta update with it tomorrow.

![View in Wunderlist](https://cloud.githubusercontent.com/assets/507058/14906078/8a5eb35c-0d85-11e6-947f-b8c09d7262f2.png)

**Comment by sollymay** [comment]
Nice!

  

Thank you so much for that feature addition!

  

That will help me a lot. Also wanted to ask you. is it possible to add an
argument when creating tasks to add notes to the task? like a 'notes' keyword
that will add a brief note or link copied from the clipboard? I normally use
wl to store links and tasks related to that link.

  

An example would be:

  

wl WebDev: due tomorrow notes change font-size to 20px on
http://www.salomonmay.com

  

That way you can both view and create notes at the same time within the same
workflow.

  

![](http://media1.giphy.com/media/pNfyBGF0rwsQ8/100.gif)  

  
Sent from [Nylas N1](https://link.nylas.com/link/ejg5mh00zu79xwfmhbchm8cs8
/local-a4c8a52a-a161/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1), the
extensible, open source mail client.  

![](https://link.nylas.com/open/ejg5mh00zu79xwfmhbchm8cs8/local-a4c8a52a-a161)

On Apr 28 2016, at 9:10 pm, Ian Paterson &lt;notifications@github.com&gt;
wrote:  

> Yep I like this. I'll release a beta update with it tomorrow.

>

> [![View in
Wunderlist](https://cloud.githubusercontent.com/assets/507058/14906078
/8a5eb35c-0d85-11e6-947f-
b8c09d7262f2.png)](https://cloud.githubusercontent.com/assets/507058/14906078
/8a5eb35c-0d85-11e6-947f-b8c09d7262f2.png)

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/94#iss
uecomment-215605886)![](https://github.com/notifications/beacon/AGMhurZJSnoUqx
kjjVefpVEE2PTdBNaEks5p8VptgaJpZM4HcG8c.gif)

**Comment by idpaterson** [comment]
It would be possible and is certainly a good idea but won't make it in 0.6.0 since the notes are not synced or modeled yet. How about for now a modifier key when entering a task that subsequently opens the task in Wunderlist? Notes are just one of many features that people might want to use so while it is important to get notes in the workflow eventually I'm in favor of adding the "open in Wunderlist" in a few key places to ease that transition.

![edit_in_wunderlist](https://cloud.githubusercontent.com/assets/507058/14915190/023f2d62-0ddf-11e6-8973-58773ef3b054.png)

The mini mode of Wunderlist is actually pretty nice for this use case.


For reference, to take a screenshot of Alfred with a modifier key (since you can't use the normal screenshot keyboard shortcuts) I did this:
```bash
sleep 5 && screencapture -iW ~/Desktop/alfred.png
```
Then got Alfred to the correct screen and modifier key state before the screenshot was taken.

**Comment by idpaterson** [comment]
The Open in Wunderlist feature has been released in [0.6.0-beta.3](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-beta.3)

**Comment by idpaterson** [comment]
Task editing within the workflow will be added in a later version, currently slated for 0.8

**Comment by blizzrdof77** [comment]
I have to ask @idpaterson - where can I download the Alfred theme in [this screenshot](https://cloud.githubusercontent.com/assets/507058/13097837/b5f65cd4-d4f2-11e5-82a5-01b1c7564741.png) as seen in your [initial comment](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/94#issue-134283101) in this issue thread?

**Comment by idpaterson** [comment]
@blizzrdof77 it is published here in #120

**Comment by blizzrdof77** [comment]
Thank you!



From: Ian Paterson <notifications@github.com> <notifications@github.com>
Reply: idpaterson/alfred-wunderlist-workflow
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 3, 2017 at 10:53:47 AM
To: idpaterson/alfred-wunderlist-workflow
<alfred-wunderlist-workflow@noreply.github.com>
<alfred-wunderlist-workflow@noreply.github.com>
Cc: Ben Wagner <benjamin.j.wagner.1@gmail.com>
<benjamin.j.wagner.1@gmail.com>, Mention <mention@noreply.github.com>
<mention@noreply.github.com>
Subject:  Re: [idpaterson/alfred-wunderlist-workflow] Task editing feature
requests (#94)

@blizzrdof77 <https://github.com/blizzrdof77> it is published here in #120
<https://github.com/idpaterson/alfred-wunderlist-workflow/issues/120>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/idpaterson/alfred-wunderlist-workflow/issues/94#issuecomment-298935265>,
or mute the thread
